### PR TITLE
fix: Ignore cloudformation validation error on not existing stacks

### LINKED ISSUE #824: Cloudformation ListStackResources validation error
### Describe the bug

While fetching stack resources validation error occur.
We need to verify if the input is wrong or aws returning 400 for non existing resource.

`Diag:aws@v0.11.1: cloudformation.stacks: failed to resolve table "aws_cloudformation_stack_resources": error at github.com/cloudquery/cq-provider-aws/resources/services/cloudformation.fetchCloudformationStackResources[stacks.go:339] operation error CloudFormation: ListStackResources, https response error StatusCode: 400, RequestID: xxxx, api error ValidationError: Stack with id xxxxxxxxx does not exist`

### Expected Behavior

fetch should not return error.

### Steps to Reproduce

fetch cloudformation stacks

### Possible Solution

_No response_

### Provider and CloudQuery version

aws@v0.11.1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zagronitay**
🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

closes #824 

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [x] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [x] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

File: client/helpers.go [hunk 1]
```diff
@@ -302,6 +302,19 @@ func IsAWSError(err error, code ...string) bool {
 	return false
 }
 
+func IgnoreCustomError(err error, code string, messageRegex string) bool {
```
Comment (disq) [inline client/helpers.go:305]: Maybe expect `*regexp.Regexp` and use that instead of compiling each time, which is costly. Ideally regexes should be compiled only once per executable invocation (using `regexp.MustCompile()` on a global variable)

File: client/helpers.go [hunk 2]
```diff
@@ -302,6 +302,19 @@ func IsAWSError(err error, code ...string) bool {
...
+	var ae smithy.APIError
+	if !errors.As(err, &ae) {
+		return false
+	}
+
+	r, _ := regexp.Compile(messageRegex)
```
Comment (disq) [inline client/helpers.go:311]: r would be nil if supplied regex wasn't valid... Better to get `*regexp.Regexp` and leave the regex validation to be early (and much faster)

**Review by disq — CHANGES_REQUESTED** [review]

**Review by disq — APPROVED** [review]
LGTM hope it works 😂

**Review by bbernays — APPROVED** [review]

**Review by disq — APPROVED** [review]
