### PR TITLE
fix: Ignore EMR block access config invalid region

### LINKED ISSUE #825: Emr public block access configuration not available in the current region.
### Describe the bug

While fetchng EMR block access configs InvalidRequestException occur.

We need to verify that this resource is available on all regions and if not to update the multiplexer.

`Diag:aws@v0.11.1: emr.block_public_access_configs: failed to resolve table "aws_emr_block_public_access_configs": error at github.com/cloudquery/cq-provider-aws/resources/services/emr.fetchEmrBlockPublicAccessConfigs[block_public_access_configs.go:113] operation error EMR: GetBlockPublicAccessConfiguration, https response error StatusCode: 400, RequestID: xxxx, InvalidRequestException: GetBlockPublicAccessConfiguration api is not available in the current Region.`

### Expected Behavior

block config should fetched without any error

### Steps to Reproduce

fetch EMR block access configs

### Possible Solution

_No response_

### Provider and CloudQuery version

aws@v0.11.1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zagronitay**
🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

closes #825 

#### Summary

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [x] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [x] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

File: resources/services/emr/block_public_access_configs.go [hunk 1]
```diff
@@ -110,6 +110,10 @@ func fetchEmrBlockPublicAccessConfigs(ctx context.Context, meta schema.ClientMet
 		options.Region = c.Region
 	})
 	if err != nil {
+		if client.IgnoreNotAvailableRegion(err) {
+			meta.Logger().Debug("received InvalidRequestException on GetBlockPublicAccessConfiguration, api is not available in the current Region.", "err", err)
```
Comment (disq) [inline resources/services/emr/block_public_access_configs.go:114]: maybe log region as well?

Comment (bbernays) [reply resources/services/emr/block_public_access_configs.go]: @disq - Could we add `region` as a default value that is included in all log messages?

**Review by disq — APPROVED** [review]

File: resources/services/emr/block_public_access_configs.go (hunk 1 above)
Comment (bbernays) [reply resources/services/emr/block_public_access_configs.go]: I am not sure the region is needed at all as it is already in all log statements: https://github.com/cloudquery/cq-provider-aws/blob/c1269e14ee46e00df1f3793e440a3b40214a7ef6/client/client.go#L262-L275

File: resources/services/emr/block_public_access_configs.go [hunk 2]
```diff
@@ -110,6 +110,10 @@ func fetchEmrBlockPublicAccessConfigs(ctx context.Context, meta schema.ClientMet
 		options.Region = c.Region
 	})
 	if err != nil {
+		if client.IgnoreNotAvailableRegion(err) {
+			meta.Logger().Debug("received InvalidRequestException on GetBlockPublicAccessConfiguration, api is not available in the current Region.", "region", c.Region, "err", err)
```
Comment (disq) [inline resources/services/emr/block_public_access_configs.go:114]:
```suggestion
			meta.Logger().Debug("received InvalidRequestException on GetBlockPublicAccessConfiguration, api is not available in the current Region.", "err", err)
```
since region is apparently in the logger anyway, I removed it

**Review by spangenberg — APPROVED** [review]
LGTM
