### PR TITLE
fix: AWS configuration error level owerwrite removed

### LINKED ISSUE #998: ACCESS level is reproted as INTERNAL
### Describe the bug

errors like below 
```
Type: Internal Severity: Error
        Summary: failed to retrieve credentials for account default. AWS Error: failed to refresh cached credentials, operation error STS: AssumeRole
, https response error StatusCode: 403, RequestID: xxxxxxxxxxxxxxxxxx, api error AccessDenied: User: xxxxxxxxxxxxxxxxxxxxxxxx is not authorized to perform: sts:AssumeRole on resource: xxxxxxxxxxxxxxxxxxxxxxxx, detecte
d aws env variables: AWS_ROLE_ARN: You are not authorized to perform this operation. Check your IAM policies, and ensure that you are using the correct access keys.

```
are classified as `INTERNAL` but they should have `ACCESS` level

### Expected Behavior

errors like below 
the error should be:
```
Type: Access Severity: Error
        Summary: failed to retrieve credentials for account default. AWS Error: failed to refresh cached credentials, operation error STS: AssumeRole
, https response error StatusCode: 403, RequestID: xxxxxxxxxxxxxxxxxx, api error AccessDenied: User: xxxxxxxxxxxxxxxxxxxxxxxx is not authorized to perform: sts:AssumeRole on resource: xxxxxxxxxxxxxxxxxxxxxxxx, detecte
d aws env variables: AWS_ROLE_ARN: You are not authorized to perform this operation. Check your IAM policies, and ensure that you are using the correct access keys.

```

### Steps to Reproduce

run `cloudquery fetch` with config that has `role_arn` set. 
example:
```
provider "aws" {
  configuration {
    accounts "default" {
      role_arn = "arn:aws:iam::test:role/service-role/test"
    }
  }
...
```

### Possible Solution

remove over severity overwriting after `configureAwsClient` func

### Provider and CloudQuery version

 aws 0.12.4

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by amanenk**
🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

closes  #998
---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [x] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [x] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

**Review by roneli — APPROVED** [review]

File: client/client.go [hunk 1]
```diff
@@ -503,7 +503,7 @@ func Configure(logger hclog.Logger, providerConfig interface{}) (schema.ClientMe
 				diags = diags.Add(diag.FromError(errors.New("unable to assume role in account"), diag.ACCESS, diag.WithSeverity(diag.WARNING)))
 				continue
 			}
-			return nil, diags.Add(classifyError(err, diag.INTERNAL, nil))
+			return nil, diags.Add(err)
```
Comment (roneli) [inline client/client.go:506]: with pass maybe as optional type?

Comment (amanenk) [reply client/client.go:506]: good suggestion
