### PR TITLE
fix: Fix panic on fetching wafv2 without us-east-1

### LINKED ISSUE #828: fetching wafv2 resources causes panic when us-east-1 region is not enabled
### Describe the bug

If a user has an explicit list of regions that does not include us-east-1 and attempts to fetch wafv2 resources then fetch will panic will "nil pointer dereference"

### Expected Behavior

Fetch should succeed.

### Steps to Reproduce

Specify "us-east-2" as only item in regions. Do a fetch for wafv2 resources.

### Possible Solution

_No response_

### Provider and CloudQuery version

latest core/aws

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by irmatov**
The bug happens when:

* user has a list of regions that doesn't include us-east-1
* wafv2 resources are fetched

The issue is that multiplexer always produces a client that has us-east-1 as a region and cloudfront scope.
When fetching starts, (*Client).Services call is made, which returns nil because there is no client for us-east-1 region.
This fix changes multiplexer to fetch cloudfront resources only when there is us-east-1 region.

Closes #828

### CODE REVIEW

**Review by roneli — APPROVED** [review]
I guess this okay seems a little like a hack

File: client/multiplexers.go [hunk 1]
```diff
@@ -59,13 +59,15 @@ func ServiceAccountRegionScopeMultiplexer(service string) func(meta schema.Clien
...
-			l = append(l, client.withAccountIDRegionAndScope(accountID, "us-east-1", wafv2types.ScopeCloudfront))
 			for region := range client.ServicesManager.services[accountID] {
 				if !isSupportedServiceForRegion(service, region) {
 					meta.Logger().Trace("region is not supported for service", "service", service, "region", region)
 					continue
 				}
+				if region == "us-east-1" {
+					// fetch cloudfront related resources only when us-east-1 is enabled
+					l = append(l, client.withAccountIDRegionAndScope(accountID, "us-east-1", wafv2types.ScopeCloudfront))
+				}
```
Comment (bbernays) [inline client/multiplexers.go:70]: Its not possible to disable `us-east-1` it is only possible to disable regions brought online after March 20, 2019:

```
Regions introduced before March 20, 2019 are enabled by default. You can begin creating and managing resources in these Regions immediately. You cannot enable or disable a Region that is enabled by default.
```

Comment (irmatov) [reply client/multiplexers.go:70]: "selected" is probably a better word. I meant like "enabled for fetching".

Comment (bbernays) [reply client/multiplexers.go:70]: I would argue that if a customer wants to grab WAF resources that should outweigh their specification of what regions to grab from. This is the same behavior that S3 has

Comment (irmatov) [reply client/multiplexers.go]: Reverted to older (desired) behavior of always fetching cloudfront scope

**Review by spangenberg — APPROVED** [review]

**Review by disq — APPROVED** [review]
