### PR TITLE
fix: Ignore apigateway model-template fetch if model not exists

### LINKED ISSUE #874: ApiGateway model template - invalid model name
### Describe the bug

While fetching apigateway rest apis NotFound error occur.

`apigateway.rest_apis: column resolver "model_template" failed for table "aws_apigateway_rest_api_models": error at github.com/cloudquery/cq-provider-aws/resources/services/apigateway.resolveApigatewayRestAPIModelModelTemplate[rest_apis.go:915] operation error API Gateway: GetModelTemplate, https response error StatusCode: 404, RequestID: xxxx, NotFoundException: Invalid model name specified: xxxxxxxxxxxxxx`

### Expected Behavior

fetch should not return error.

### Steps to Reproduce

fetch apigateways rest apis

### Possible Solution

_No response_

### Provider and CloudQuery version

aws@v0.11.3

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zagronitay**
🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

closes #874 
---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [x] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [x] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

File: resources/services/apigateway/rest_apis.go [hunk 1]
```diff
@@ -912,6 +912,10 @@ func resolveApigatewayRestAPIModelModelTemplate(ctx context.Context, meta schema
 			// select * from aws_apigateway_rest_api_models where model_template is nil
 			return nil
 		}
+		if cl.IsNotFoundError(err) {
+			meta.Logger().Debug("GetModelTemplate: model does not exist", "err", err)
```
Comment (disq) [inline resources/services/apigateway/rest_apis.go:916]: cl.IsNotFoundError already logs, so no need for the log?

**Review by disq — APPROVED** [review]
