### PR TITLE
Use specified regions to detect available regions

### LINKED ISSUE #242: Disabled regions detection is using hardcoded region "us-east-1" that could be a disabled region in some configurations
### Describe the Bug
In some configurations, accounts could be regional and thus could not use the region "us-east-1", disabled by Service control policies (SCPs).

screenshot_318

### Expected Behavior
If regions are specified in the config.hcl, the use of _DescribeRegions_ to detect disable regions should use one of them. 

### CloudQuery Version
cq-provider-aws v0.6.0

### Debug Output

cloudquery-AWS-disabledRegion

### Steps to Reproduce
Use of the following configuration with an account limited to these regions :
```
provider "aws" {
  configuration {
    // Optional. if you want to assume role to multiple account and fetch data from them
    //accounts "<YOUR ID>" {
    // Optional. Role ARN we want to assume when accessing this account
    // role_arn = <YOUR_ROLE_ARN>
    // }
    regions = ["eu-west-3", "eu-central-1"]
    // Optional. Enable AWS SDK debug logging.
    aws_debug = true
  }
```

### Additionnal content
I will probably do a PR for this one. I might have the time for it.

### References
https://github.com/cloudquery/cq-provider-aws/issues/39

### PR DESCRIPTION
**Pull request by spangenberg**
Fallback to default region

Fixes #242

### CODE REVIEW

File: client/client.go [hunk 1]
```diff
@@ -355,7 +355,11 @@ func Configure(logger hclog.Logger, providerConfig interface{}) (schema.ClientMe
 		res, err := ec2.NewFromConfig(awsCfg).DescribeRegions(ctx,
 			&ec2.DescribeRegionsInput{AllRegions: aws.Bool(false)},
 			func(o *ec2.Options) {
-				o.Region = "us-east-1"
+				if len(awsConfig.Regions) > 0 {
+					o.Region = awsConfig.Regions[0]
+				} else {
+					o.Region = defaultRegion
+				}
```
Comment (roneli) [inline client/client.go:362]:
```suggestion
				o.Region = defaultRegion
				if len(awsConfig.Regions) > 0 {
					o.Region = awsConfig.Regions[0]
				} 
```

**Review by roneli — APPROVED** [review]
LGTM, had a minor suggestion, tell me what you think, and we can merge.
