### PR TITLE
fix: Classify auth failure

### LINKED ISSUE #897: Classify Failed to refresh as Access diag
### Describe the bug

failed to retrieve credentials for account . AWS Error: failed to refresh cached credentials, the SSO session has expired or is invalid: access token is expired, detected aws env variables: AWS_PROFILE,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_SESSION_TOKEN

Is classified as an internal error

### Expected Behavior

Classify this error as Access

### Steps to Reproduce

Run CQ AWS provider with SSO session expired

### Possible Solution

_No response_

### Provider and CloudQuery version

v0.23.0

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by roneli**
classify auth failure

Closes https://github.com/cloudquery/cq-provider-aws/issues/897 as well

### CODE REVIEW

File: client/errors.go [hunk 1]
```diff
@@ -61,6 +63,19 @@ func classifyError(err error, fallbackType diag.Type, accounts []Account, opts .
...
 		}
+		if ae.ErrorMessage() == ssoInvalidOrExpired {
+			return diag.Diagnostics{
+				RedactError(accounts, diag.NewBaseError(err,
+					diag.ACCESS,
+					append(opts,
+						diag.WithType(diag.ACCESS),
+						diag.WithSeverity(diag.WARNING),
+						ParseSummaryMessage(err),
+						diag.WithDetails(errorCodeDescriptions[ae.ErrorCode()]),
```
Comment (disq) [inline client/errors.go:74]: add `AuthFailure` to `errorCodeDescriptions`?

Comment (roneli) [reply client/errors.go:74]: added

**Review by disq — APPROVED** [review]

**Review by bbernays — APPROVED** [review]
