### PR TITLE
Cloudtrail tags fix

### LINKED ISSUE #236: Bug: CloudTrailARNInvalidException: Region ian ARN is wrong, you can only access resources in region us-east-1.
### Describe the Bug
Running cloudquery fetch with vanilla configuration returns the following error

```
Table: aws_cloudtrail_trails                                            Error: table resolver ignored error: operation error CloudTrail: ListTags, https response error StatusCode: 400, RequestID: 00973b0d-3012-4a98-b9b9-c2b436727b05, CloudTrailARNInvalidException: Region in ARN is wrong, you can only access resources in region us-east-1.
```

### Expected Behavior
Not seeing this error

### CloudQuery Version
Version: 0.15.9
Commit: f6c9b4772fe815af8d7488af6d088a463e5fa157
Date: 2021-11-01 10:05:06.199344 +0200 IST m=+0.051294064

### Steps to Reproduce
```
cloudquery init
cloudquery fetch
```

### PR DESCRIPTION
**Pull request by fdistorted**
cloudtrails tag list sometimes returned the error because region in cloudtrail ARN and in call options were different. Now cloudtrails are aggregated by region before doing get tags call.
fixes #236

### CODE REVIEW

**Review by roneli — APPROVED** [review]
LGTM

File: resources/cloudtrail_trails.go [hunk 1]
```diff
@@ -380,6 +386,14 @@ func getCloudTrailTagsByResourceID(id string, set []types.ResourceTag) []types.T
 	return nil
 }
 
+func aggregateCloudTrails(trails []types.Trail) map[string][]types.Trail {
+	resp := make(map[string][]types.Trail)
+	for _, t := range trails {
+		resp[*t.HomeRegion] = append(resp[*t.HomeRegion], t)
```
Comment (yevgenypats) [inline resources/cloudtrail_trails.go:392]: I think a `nil` check is missing here
