### PR TITLE
fixed pk error - secretmanager

### LINKED ISSUE #354: Duplicate key on secret manager resource
### Describe the Bug
Secret manager resource has duplicate key inserted, ARN might not be unique enough, and we might require account_id/region. Double check if this is a per region resource or not.

### Expected Behavior
No duplicate keys

### CloudQuery Version
v0.17.3

### PR DESCRIPTION
**Pull request by zagronitay**
Relates OR Closes #354 

Output from acceptance testing:
More information about running the tests [here](../docs/contributing/e2e_tests.md)

```
$ make testName=TestAccXXX e2e-test-with-apply
...
```

### CODE REVIEW

**Review by spangenberg — APPROVED** [review]
LGTM

File: resources/secretsmanager_secrets.go [hunk 1]
```diff
@@ -164,7 +164,7 @@ func fetchSecretsmanagerSecrets(ctx context.Context, meta schema.ClientMeta, _ *
 			}
 
 			secret := WrappedSecret{
-				SecretListEntry:   &n,
```
Comment (disq) [inline resources/secretsmanager_secrets.go:167]: Not sure if it'll work as `range` re-uses the value. Adding a `n := n` before, or accessing the element with `response.SecretList[i]` would be safer.

**Review by disq — APPROVED** [review]

File: resources/secretsmanager_secrets.go [hunk 2]
```diff
@@ -152,7 +152,7 @@ func fetchSecretsmanagerSecrets(ctx context.Context, meta schema.ClientMeta, _ *
 
 		// get more details about the secret
 		for _, n := range response.SecretList {
```
Comment (roneli) [inline resources/secretsmanager_secrets.go:154]: would create a list of secret entries and pass them as one to channel instead of one by one, that would have also avoided this PK issue, you can keep this fix as well.

**Review by roneli — CHANGES_REQUESTED** [review]

**Review by roneli — APPROVED** [review]
