### PR TITLE
Fix call to ListAccounts in a non-org user

### LINKED ISSUE #254: Trying to call ListAccounts in a non-org user
### Describe the Bug
Currently ListAccounts is getting called on all accounts without any filter. Which produces the following warning:

```
Access Severity: Warning
Summary: Organizations: ListAccounts - You don't have permissions to access this resource.
Remediation: You are not authorized to perform this operation. Check your IAM policies, and ensure that you are using the correct access keys.
```

### Expected Behavior
Not calling ListAccounts in non-org user (research if there is a way to test it first if we are in a non org-user)

### CloudQuery Version
Version: 0.15.10
Commit: 00e576804344a17360d3ad94f79f6b30a4118c78
Date: 2021-11-14 09:54:28.360668 +0200 IST m=+0.005966954

### Steps to Reproduce
```
cloudquery fetch # using assume role
```

### PR DESCRIPTION
**Pull request by spangenberg**
The error might not be IAM policy related and needs to be treated
independent from the rest.

Fixes #254

### CODE REVIEW

**Review by roneli — APPROVED** [review]
LGTM

**Comment by roneli** [comment]
Another option, before I merge this, we can return that error from the resolver keeping the error classifier clean and generic. Wdyt?

File: client/errors.go [hunk 1]
```diff
@@ -5,41 +5,48 @@ import (
...
 )
 
 func ErrorClassifier(meta schema.ClientMeta, resourceName string, err error) []diag.Diagnostic {
 	client := meta.(*Client)
+	var ee *diag.ExecutionError
+	if errors.As(err, &ee) {
+		return []diag.Diagnostic{
+			ee,
+		}
+	}
```
Comment (roneli) [inline client/errors.go:20]: No need for this its already checked in https://github.com/cloudquery/cq-provider-sdk/blob/be1cd34f3527c627c1c7d814c5f4c90d3979e0aa/provider/provider.go#L247

**Review by roneli — CHANGES_REQUESTED** [review]

**Review by roneli — APPROVED** [review]
LGTM, tests pass and merge
