### PR TITLE
fix: Ignore organization tail tags if permissions are missing

### LINKED ISSUE #405: cloudtrail.trails configuration ingestion needs to be aware of Organization-wide trails
### Describe the bug

The `fetch` operation fails for resource type `cloudtrail.trails` when an AWS account is part of an AWS Organization that has deployed an Organization-wide CloudTrail.

Specifically, `fetch` generates an error when it tries to ListTags for an Organization-wide CloudTrail which has an ARN that lies outside of the target AWS account.
```
Resource: cloudtrail.trails Type: Resolving Severity: Error
        Summary: table resolve error: operation error CloudTrail: ListTags, https response error StatusCode: 400, RequestID: dee43178-c3ca-49da-875f-9c05f12fed1c, CloudTrailARNInvalidException: AccountID in ARN is wrong, you can only access resources with AccountID 123456789012.
```

### Expected Behavior

`fetch` should be able to:
- collect the basic properties of even an Organization-wide CloudTrail; those basic properties may not include the tags if IAM privs don't allow that.
- should attempt to collect all the properties (including Tags) of a CloudTrail and only gracefully fail when/if IAM privs don't allow those properties to be collected

### Steps to Reproduce

1. Create an AWS Organization
2. Create an Organization-wide CloudTrail in the Org master account
3. Create at least one linked account in the Org
4. Run `cloudquery fetch` in the linked account

### Possible Solution

_No response_

### Provider and CloudQuery version

CQ version: 0.19.0, cq-provider-aws version: 0.9.0

### Additional Context

Version: 0.19.0
Commit: feadfa6746827cb975797f1f2ba70b5aa1f9643a
Date: 2022-01-13 15:06:24.686643064 +0000 UTC m=+0.014267283

This error was generated while using the ghcr.io/cloudquery/cloudquery:0.19.0 Docker image.

### PR DESCRIPTION
**Pull request by zagronitay**
- [ ] Relates OR Closes #405 
- [ ] Added integration tests as described [here](https://docs.cloudquery.io/docs/developers/sdk/testing)

Output from integration tests:
More information about running the tests [here](../docs/contributing/e2e_tests.md)

```
$ go test -tags=integration ./...

```

### CODE REVIEW

File: resources/services/cloudtrail/trails.go [hunk 1]
```diff
@@ -225,47 +226,65 @@ func CloudtrailTrails() *schema.Table {
...
-				options.Region = region
-			})
+
+		for i, h := range trails {
+			processed[i] = CloudTrailWrapper{
+				Trail: h,
+				Tags:  make(map[string]interface{}),
+			}
+
+			// Before fetching trail tags we have to check if the trail is organization tail
```
Comment (zagronitay) [inline resources/services/cloudtrail/trails.go:251]: typo :|

File: resources/services/cloudtrail/trails.go [hunk 2]
```diff
@@ -225,47 +226,65 @@ func CloudtrailTrails() *schema.Table {
...
+					options.Region = region
+				})
+				if err != nil {
+					return nil, err
 				}
-				for _, t := range getCloudTrailTagsByResourceID(*tr.TrailARN, response.ResourceTagList) {
-					wrapper.Tags[*t.Key] = t.Value
+				for _, tr := range processed {
+					for _, t := range getCloudTrailTagsByResourceID(*tr.TrailARN, response.ResourceTagList) {
+						tr.Tags[*t.Key] = t.Value
```
Comment (bbernays) [inline resources/services/cloudtrail/trails.go:278]: I can't remember but will this update the variable `processed` in a way that it will eventually be returned?

Comment (bbernays) [reply resources/services/cloudtrail/trails.go:278]: Don't remember if it is a shallow or deep copy

Comment (bbernays) [reply resources/services/cloudtrail/trails.go:277]: Tested this out locally. It works as expected

File: resources/services/cloudtrail/trails.go [hunk 3]
```diff
@@ -225,47 +226,64 @@ func CloudtrailTrails() *schema.Table {
...
-				res <- wrapper
-			}
-
-			if aws.ToString(response.NextToken) == "" {
-				break
+				if aws.ToString(response.NextToken) == "" {
+					break
+				}
+				input.NextToken = response.NextToken
 			}
```
Comment (bbernays) [inline resources/services/cloudtrail/trails.go:284]: Can we just return early if input list is empty?

Then you can do a while loop for  `response.NextToken  == ""`

**Review by bbernays — COMMENTED** [review]
LGTM other than single suggestion

**Review by bbernays — APPROVED** [review]
LGTM 🚢 🚀

**Review by roneli — APPROVED** [review]
LGTM 🚀
