### PR TITLE
fix: Update timestamps fields

### LINKED ISSUE #813: Handle timestamps/datetimes uniformly across all resources
### Describe the bug

In some resources, timestamps are treated as [integers](https://github.com/cloudquery/cq-provider-aws/blob/main/resources/services/sqs/queues.go#L78). In others, they're treated as [strings](https://github.com/cloudquery/cq-provider-aws/blob/main/resources/services/ec2/images.go#L60). In some places, they're treated as [timestamps](https://github.com/cloudquery/cq-provider-aws/search?q=schema.TypeTimestamp)

### Expected Behavior

All timestamps in aws services fetched by cloudquery-provider-aws are expressed in the same schema.

### Steps to Reproduce

Setup cloudquery, initialize the database and inspect the schemas of aws_ec2_images, aws_sqs_queues, and aws_sns_topics. 

There are many other examples as well

### Possible Solution

My preferred solution would be that all timestamps/datetimes are all treated as timestamps.

### Provider and CloudQuery version

Version: 0.22.7 Commit: fb5a1447e0851d96af0fb7d522585bf78566ff3f Date: 2022-04-19T08:55:30Z v0.11.1

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by zagronitay**
🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

closes #813 
---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [x] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [x] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by disq — APPROVED** [review]
LGTM

File: resources/services/lambda/layers.go [hunk 1]
```diff
@@ -42,8 +47,8 @@ func LambdaLayers() *schema.Table {
 			{
 				Name:        "latest_matching_version_created_date",
 				Description: "The date that the version was created, in ISO 8601 format",
-				Type:        schema.TypeString,
-				Resolver:    schema.PathResolver("LatestMatchingVersion.CreatedDate"),
+				Type:        schema.TypeTimestamp,
+				Resolver:    client.ResolveTimestampField("LatestMatchingVersion.CreatedDate", TimestampLayoutNano),
```
Comment (bbernays) [inline resources/services/lambda/layers.go:51]: Do you have to update the `gen.hcl` file?

**Review by bbernays — APPROVED** [review]
